version: "3"
services:
  backend:
    build:
      context: ./back-end
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app:cached
      - /app/node_modules
    labels:
      - "prometheus_job=backend"

  frontend:
    build:
      context: ./front-end
    ports:
      - "8081:8080"
    volumes:
      - ./front-end:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    labels:
      - "prometheus_job=frontend"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9091:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9090"
