version: "3"
services:
  backend:
    build:
      context: ./back-end
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app:cached
      - /app/node_modules

  frontend:
    build:
      context: ./front-end
    ports:
      - "8080:8080"
    volumes:
      - ./front-end:/app:cached
      - /app/node_modules
    depends_on:
      - backend
